#!/bin/bash

#WARNING: DO NOT RUN THIS FILE DIRECTLY
#  This file expects to be a part of libservicelog test suite
#  Run this file with ../run_tests -t test-004-log_encl_event -q


# Clear all old events(Truncate events)
truncate_events
log_event "$SERVICELOG_EVENT_ENCL"
